# Generated by Django 2.2.3 on 2019-07-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startday', models.CharField(blank=True, max_length=20)),
                ('endday', models.CharField(blank=True, max_length=20)),
                ('starttime', models.CharField(blank=True, max_length=10)),
                ('endtime', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
